name: test

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

env:
  BUILD_TAG: anonaddy:test
  CONTAINER_NAME: anonaddy
  RUNNING_TIMEOUT: 120
  RUNNING_LOG_CHECK: "ready to handle connections"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
      -
        name: Create network
        run: |
          docker network create -d bridge ${{ env.CONTAINER_NAME }}
      -
        name: Start MariaDB container
        run: |
          docker run -d --name mariadb --hostname mariadb \
            --network ${{ env.CONTAINER_NAME }} \
            -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" \
            -e "MYSQL_DATABASE=anonaddy" \
            -e "MYSQL_USER=anonaddy" \
            -e "MYSQL_PASSWORD=anonaddy" \
            mariadb:10.5
      -
        name: Generate DKIM private key
        run: |
          docker run --rm -t --entrypoint "" \
            -e "ANONADDY_DOMAIN=example.com" \
            -v "/tmp/data:/data" \
            ${{ env.BUILD_TAG }} gen-dkim
      -
        name: Start container
        run: |
          docker run -d --name ${{ env.CONTAINER_NAME }} \
            --link mariadb \
            --network ${{ env.CONTAINER_NAME }} \
            -e "DB_HOST=mariadb" \
            -e "DB_DATABASE=anonaddy" \
            -e "DB_USERNAME=anonaddy" \
            -e "DB_PASSWORD=anonaddy" \
            -e "APP_KEY=base64:Gh8/RWtNfXTmB09pj6iEflt/L6oqDf9ZxXIh4I9MS7A=" \
            -e "ANONADDY_DOMAIN=example.com" \
            -e "ANONADDY_SECRET=0123456789abcdefghijklmnopqrstuvwxyz" \
            -e "RSPAMD_ENABLE=true" \
            -v "/tmp/data:/data" \
            ${{ env.BUILD_TAG }}
      -
        name: Test run
        run: |
          TIMEOUT=$((SECONDS + ${{ env.RUNNING_TIMEOUT }}))
          while read LOGLINE; do
            echo ${LOGLINE}
            if [[ ${LOGLINE} == *"${{ env.RUNNING_LOG_CHECK }}"* ]]; then
              echo "🎉 Container up!"
              break
            fi
            if [[ $SECONDS -gt ${TIMEOUT} ]]; then
              >&2 echo "❌ Failed to run ${{ env.CONTAINER_NAME }} container"
              exit 1
            fi
          done < <(docker logs -f ${{ env.CONTAINER_NAME }} 2>&1)

          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ env.CONTAINER_NAME }})
          if [[ ${CONTAINER_STATUS} != "running" ]]; then
            >&2 echo "❌ Container ${{ env.CONTAINER_NAME }} returned status '$CONTAINER_STATUS'"
            exit 1
          fi
      -
        name: Logs
        if: always()
        run: |
          docker logs ${{ env.CONTAINER_NAME }}
          docker rm -f ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
